### DISCUSSION TITLE
fetch image from style: background-image

### DISCUSSION THREAD

**Discussion by haayman** [html2rss/html2rss.github.io#724] [Q&A] [answered]
I'm trying to create an rss feed from https://www.salland1.nl/category/deventer/ (they used to have a regular RSS :-( )
The image is hidden in the style attribute
```
<span
     class="entry-thumb td-thumb-css"
     style="background-image: url('https://www.salland1.nl/wp-content/uploads/2021/01/Subsidies-en-leningen-voor-energiebesparing.jpg');">
</span>                                  
```
So I'm trying this in feeds.yml
```
      enclosure:
        selector: "span.entry-thumb"
        extractor: "attribute"
        attribute: "style"
        post_process:
          - name: gsub
            pattern: "background-image: url\('"
            replace: ""
          -name: gsub
            pattern: "');"
            replace: ""

```
I've also tried gsub using a regex, but I could't figure out how to declare that in yaml
This doesn't do anything. The resulting rss doesn't have an enclosement.
Any suggestions on how to do this?

**Comment by gildesmarais** [comment, marked as answer]
Hej / Moin, 
sorry took me a while to get back.

Little issues with your config, here's the corrected one:

```yml
channel:
  url: https://www.salland1.nl/category/deventer/
  title: Salland1 Deventer
  description: Nieuws uit Deventer
selectors:
  items:
    selector: '.td-cpt-post'
  title:
    selector: 'a[title]'
    extractor: attribute
    attribute: title
  url:
    selector: 'a'
    extractor: href
  enclosure:
    selector: "span.entry-thumb"
    extractor: "attribute"
    attribute: "style"
    post_process:
      - name: gsub
        pattern: "background-image: url\\([']?"
        replacement: ""
      - name: gsub
        pattern: "[']?\\)"
        replacement: ""

```

Their markup seems skipp `'` in the background-image's url.
Also `gsub` needs a `replacement`.

I figure the variable name is a bit too verbose :)
